### ISSUE TITLE
Exception communicating with daemon

### ISSUE THREAD

**Issue by 07BC** [johnno1962/Refactorator#1]
Love the idea of the plugin! 

Just installed it and tried to refactor a class name and got the following error.

`Exception communicating with daemon: connection went invalid while waiting for a reply because a mach port died`

Tried renaming a method and got the following. 

`Source index error: Optional("Connection interrupted")`

This is on Xcode 7.2, using latest Alcatraz

**Comment by johnno1962** [comment]
Hi, thanks for letting e know,  not seen this at all. sounds like both the daemon and sourcekit crashed. Is there any chance you’d be able to send me the project you’re working on? injectionforxcode at johnholdsworth.com

**Comment by johnno1962** [comment]
Hmm, I figured that might have been quite an ask. I think this is just Sourcekit crashing without knowing more about your project. If anybody else see this problem could they log it here please. I’ve tested exhaustively with “Lister” and not seen a crash myself.

**Comment by johnno1962** [comment]
Hi Jamie, I’ve been testing with a larger project (https://github.com/artsy/eidolon) and I’ve found one way to get this message is to interrrupt the daemon before it’s finished indexing. I’ve modified the interface to make it more obvious when indexing is in progress and more difficult to interupt if you want to give it another try.

**Comment by johnno1962** [comment]
I’ve rewritten the plugin to not use SourceKit so this may be resolved. Do you want to give it a try with the new version?
