### ISSUE TITLE
Add ability to set key binding for refactoring

### ISSUE THREAD

**Issue by mr-v** [johnno1962/Refactorator#4]
Hi,
great plugin, many thanks for it!

I have a little request: it would be nice to have an ability to hit keyboard shortcut as an alternative to "Right-click/Refactor/Swift !".

**Comment by johnno1962** [comment]
Hi, you should be able to do this with the System Preferences/Keyboard/App Shortcuts panel e.g. ![shortcut](https://cloud.githubusercontent.com/assets/1786033/12243180/0a0839ac-b895-11e5-93f8-7caaceb22250.png)

**Comment by mr-v** [comment]
Great, thanks for the tip.
